export type CharacterGroup = {
  id: string;
  label: string;
  /** Suchbegriffe je Zeichen, damit die Suche auf Deutsch funktioniert. */
  items: { char: string; keywords: string }[];
};

function group(id: string, label: string, entries: [string, string][]): CharacterGroup {
  return {
    id,
    label,
    items: entries.map(([char, keywords]) => ({ char, keywords })),
  };
}

export const CHARACTER_GROUPS: CharacterGroup[] = [
  group("haeufig", "Häufig", [
    ["✅", "haken check erledigt ja"],
    ["✨", "funkeln neu glitzer"],
    ["🔥", "feuer hot angesagt"],
    ["⭐", "stern bewertung top"],
    ["👉", "finger zeigen hinweis rechts"],
    ["💡", "idee tipp gluehbirne"],
    ["🎯", "ziel treffer zielgruppe"],
    ["⏰", "wecker zeit frist deadline"],
    ["💰", "geld preis sparen budget"],
    ["🚀", "rakete start wachstum schnell"],
    ["❤️", "herz liebe favorit"],
    ["👍", "daumen gut like"],
    ["⚡", "blitz schnell energie"],
    ["🎁", "geschenk aktion gratis"],
    ["📈", "wachstum steigend erfolg chart"],
    ["🛒", "einkaufswagen warenkorb shop"],
  ]),
  group("smileys", "Smileys & Gesten", [
    ["😀", "lachen freude smiley"],
    ["😃", "lachen freude"],
    ["😄", "lachen freude"],
    ["😁", "grinsen zaehne"],
    ["😊", "laecheln freundlich"],
    ["🙂", "laecheln leicht"],
    ["😉", "zwinkern augenzwinkern"],
    ["😍", "verliebt herzaugen begeistert"],
    ["🥰", "verliebt herzen"],
    ["😎", "sonnenbrille cool"],
    ["🤩", "sterne begeistert wow"],
    ["🥳", "party feiern jubilaeum"],
    ["🤔", "nachdenken frage ueberlegen"],
    ["😮", "ueberrascht staunen"],
    ["😅", "schwitzen lachen erleichtert"],
    ["🙌", "haende jubel erfolg"],
    ["👏", "klatschen applaus"],
    ["👋", "winken hallo gruss"],
    ["💪", "muskel stark kraft"],
    ["🤝", "handschlag partner deal"],
    ["🙏", "danke bitte haende"],
    ["👀", "augen schauen achtung"],
    ["🫵", "zeigen du"],
    ["✌️", "peace victory"],
  ]),
  group("symbole", "Symbole", [
    ["✔️", "haken check erledigt"],
    ["☑️", "kaestchen haken checkbox"],
    ["❌", "kreuz falsch nein"],
    ["✖️", "kreuz mal"],
    ["⭕", "kreis richtig"],
    ["❗", "ausrufezeichen achtung"],
    ["❓", "fragezeichen frage"],
    ["⚠️", "warnung achtung"],
    ["🔴", "punkt rot live"],
    ["🟢", "punkt gruen verfuegbar"],
    ["🔵", "punkt blau"],
    ["🟡", "punkt gelb"],
    ["💯", "hundert prozent volle punktzahl"],
    ["🆕", "neu new"],
    ["🆓", "gratis kostenlos free"],
    ["🔒", "schloss sicher datenschutz"],
    ["🔓", "offen entsperrt"],
    ["♻️", "recycling nachhaltig gruen"],
    ["🏆", "pokal gewinner bester"],
    ["🎉", "party konfetti feiern"],
    ["🎊", "konfetti feiern"],
    ["⏳", "sanduhr zeit knapp"],
    ["🔔", "glocke erinnerung benachrichtigung"],
    ["©️", "copyright"],
  ]),
  group("business", "Business & Objekte", [
    ["💼", "koffer business arbeit"],
    ["📊", "diagramm statistik daten"],
    ["📉", "fallend sinkend verlust"],
    ["💳", "karte zahlung kreditkarte"],
    ["🛍️", "einkaufstasche shopping"],
    ["📦", "paket versand lieferung"],
    ["🚚", "lkw lieferung versand"],
    ["🏷️", "preisschild rabatt tag"],
    ["📱", "handy smartphone mobil"],
    ["💻", "laptop computer online"],
    ["🖥️", "monitor desktop"],
    ["📷", "kamera foto"],
    ["🎥", "video kamera film"],
    ["📢", "megafon ankuendigung news"],
    ["📣", "megafon werbung laut"],
    ["✉️", "brief mail nachricht"],
    ["📩", "mail eingang nachricht"],
    ["🔗", "link kette verweis"],
    ["📌", "pin merken wichtig"],
    ["📍", "standort ort adresse"],
    ["🗓️", "kalender termin datum"],
    ["⏱️", "stoppuhr schnell zeit"],
    ["🔍", "lupe suchen finden"],
    ["🧾", "beleg rechnung quittung"],
  ]),
  group("leben", "Natur, Essen & Reise", [
    ["🌱", "pflanze wachstum start"],
    ["🌿", "blatt natur gruen"],
    ["🌸", "bluete fruehling"],
    ["🌞", "sonne sommer"],
    ["🌙", "mond nacht"],
    ["🌈", "regenbogen vielfalt"],
    ["🍀", "kleeblatt glueck"],
    ["🍎", "apfel obst gesund"],
    ["🍕", "pizza essen"],
    ["☕", "kaffee pause"],
    ["🍰", "kuchen suess"],
    ["🥗", "salat gesund"],
    ["✈️", "flugzeug reise urlaub"],
    ["🚗", "auto fahren"],
    ["🏠", "haus zuhause immobilie"],
    ["🏢", "gebaeude buero firma"],
    ["🌍", "welt global erde"],
    ["🗺️", "karte reise plan"],
  ]),
  group("pfeile", "Pfeile", [
    ["→", "pfeil rechts"],
    ["←", "pfeil links"],
    ["↑", "pfeil hoch"],
    ["↓", "pfeil runter"],
    ["↔", "pfeil beide"],
    ["⇒", "pfeil doppelt folgt"],
    ["➡️", "pfeil rechts emoji"],
    ["⬅️", "pfeil links emoji"],
    ["⬆️", "pfeil hoch emoji"],
    ["⬇️", "pfeil runter emoji"],
    ["↗️", "pfeil schraeg hoch steigend"],
    ["↘️", "pfeil schraeg runter"],
    ["▶️", "play abspielen dreieck"],
    ["➤", "pfeilspitze aufzaehlung"],
    ["❯", "chevron rechts"],
    ["»", "doppelpfeil rechts guillemet"],
    ["«", "doppelpfeil links guillemet"],
  ]),
  group("aufzaehlung", "Aufzählung & Linien", [
    ["•", "punkt aufzaehlung bullet"],
    ["◦", "kreis klein aufzaehlung"],
    ["‣", "dreieck aufzaehlung"],
    ["▪", "quadrat klein aufzaehlung"],
    ["▫", "quadrat weiss klein"],
    ["■", "quadrat gefuellt"],
    ["□", "quadrat leer"],
    ["●", "kreis gefuellt"],
    ["○", "kreis leer"],
    ["★", "stern gefuellt"],
    ["☆", "stern leer"],
    ["✦", "stern vierzackig"],
    ["✓", "haken ascii check"],
    ["✗", "kreuz ascii"],
    ["–", "gedankenstrich halbgeviert en dash"],
    ["—", "gedankenstrich geviert em dash"],
    ["―", "linie lang"],
    ["·", "mittelpunkt trenner"],
    ["…", "auslassungspunkte drei punkte"],
    ["│", "linie senkrecht"],
    ["─", "linie waagerecht"],
  ]),
  group("typografie", "Typografie & Einheiten", [
    ["„", "anfuehrungszeichen unten deutsch"],
    ["“", "anfuehrungszeichen oben deutsch"],
    ["”", "anfuehrungszeichen englisch"],
    ["‚", "einfaches anfuehrungszeichen unten"],
    ["‘", "einfaches anfuehrungszeichen oben"],
    ["‹", "spitzklammer links einfach"],
    ["›", "spitzklammer rechts einfach"],
    ["€", "euro waehrung preis"],
    ["$", "dollar waehrung"],
    ["£", "pfund waehrung"],
    ["%", "prozent rabatt"],
    ["‰", "promille"],
    ["№", "nummer nr"],
    ["§", "paragraf recht"],
    ["®", "registered marke"],
    ["™", "trademark marke"],
    ["°", "grad temperatur"],
    ["±", "plusminus etwa"],
    ["×", "mal multiplikation"],
    ["÷", "geteilt division"],
    ["≈", "ungefaehr etwa"],
    ["≠", "ungleich"],
    ["≤", "kleiner gleich"],
    ["≥", "groesser gleich"],
    ["½", "halb bruch"],
    ["¼", "viertel bruch"],
    ["¾", "dreiviertel bruch"],
    ["→", "pfeil rechts"],
    [" ", "geschuetztes leerzeichen nbsp"],
  ]),
];

let segmenter: Intl.Segmenter | null = null;

/**
 * Zählt sichtbare Zeichen statt UTF-16-Einheiten. Ein Emoji wie 👍 belegt zwei
 * Einheiten, 👨‍👩‍👧 sogar acht – ohne Segmenter läge der Zähler bei Texten mit
 * Emojis deutlich über der tatsächlichen Länge, und genau daran hängen die
 * Zeichenvorgaben in den Prompts.
 */
export function countCharacters(text: string): number {
  if (typeof Intl !== "undefined" && typeof Intl.Segmenter === "function") {
    segmenter ??= new Intl.Segmenter("de", { granularity: "grapheme" });
    let count = 0;
    for (const _segment of segmenter.segment(text)) count += 1;
    return count;
  }
  return text.length;
}
